baseURL = "https://juanfrancoyu.com/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo (Themefisher)"
title = "Juan Franco Yu — Full-stack Digital Marketer"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = "2"
[[menu.main]]
URL = "tools"
name = "Tools"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = "1"
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Juan Franco Yu"
contact_form_action = "#"
copyright = "© Juan Franco Yu — Full-stack Digital Marketer"
description = "Full-stack Digital Marketer. Simplifying complex business problems using words and design."
google_tag_manager = ""
home = "Home"
logo = "/images/logo-1.svg"
[params.banner]
bgImage = "/images/banner/banner-bg.svg"
image = "/images/illustration.svg"
title = "Do customers cringe when they land on your website? It's not your fault. "
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
